-- P0-04 — Private media protection for the "Paylaşımlar" (activity_posts) feed.
--
-- BEFORE: the `activity-posts` Storage bucket was PUBLIC and had an anonymous
-- read policy, so every post photo — including photos on is_public = false
-- posts — was reachable by anyone with (or guessing) the URL, and the bucket
-- was anonymously listable. That directly breaks the "your content is private"
-- promise.
--
-- AFTER: the bucket is PRIVATE. Anonymous access is gone. Only the owner can
-- read (and therefore mint signed URLs for) their own objects. The app now
-- stores a long-lived *signed* URL on the row at upload time (see
-- posts_repository.dart), so viewers of a public post still see the photo, but
-- nobody can browse the raw bucket and no is_public = false photo leaks.
--
-- Safe to run multiple times.

-- 1) Flip the bucket to private ---------------------------------------------
update storage.buckets set public = false where id = 'activity-posts';

-- 2) Replace the wide-open policies with owner-scoped ones -------------------

-- Upload: only into your own top-level folder (paths are `<uid>/<file>`).
drop policy if exists "upload post photos" on storage.objects;
create policy "upload own post photos" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'activity-posts'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Read: owner only. (Signed URLs generated by the owner at upload time keep
-- working for everyone; this policy only governs who can *mint* new ones and
-- kills the old anonymous read.)
drop policy if exists "read post photos" on storage.objects;
create policy "read own post photos" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'activity-posts'
    and owner = auth.uid()
  );

-- Update / delete: owner only, so people can only manage their own photos.
drop policy if exists "update own post photos" on storage.objects;
create policy "update own post photos" on storage.objects
  for update to authenticated
  using (bucket_id = 'activity-posts' and owner = auth.uid());

drop policy if exists "delete own post photos" on storage.objects;
create policy "delete own post photos" on storage.objects
  for delete to authenticated
  using (bucket_id = 'activity-posts' and owner = auth.uid());

-- NOTE on old data: photos uploaded before this migration have a *public* URL
-- stored on their row and will stop loading once the bucket is private. That's
-- the intended "close the hole" behaviour. If you want to keep old test posts
-- visible, delete them and re-post; new posts use signed URLs automatically.
